
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 08/05/2021 21:01:07
 *    Problem Name  : A. Lucky Conversion
 *    Problem Limit : 2000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/145/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int
using namespace std;

void solve()
{
    string s1,s2;
    cin >> s1 >> s2;

    ll cnt_seven = 0, cnt_four = 0;

    for(ll i=0; i<s1.length(); i++) {
        if(s1[i] != s2[i]) {
            if(s1[i] == '4') cnt_four++;
            else cnt_seven++;
        }
    }

    cout << max(cnt_seven, cnt_four) << endl;
}

int main(){
    ios_base::sync_with_stdio(false);
    solve();
    return 0 ;
}
