
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 05/05/2021 11:40:37
 *    Problem Name  : B. The Cake Is a Lie
 *    Problem Limit : 2000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/contest/1519/problem/B
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n,m,k;
    cin >> n >> m >> k;

    if(k == (n*m)-1) cout << "YES" << endl;
    else cout << "NO" << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--){
        solve();
    }

    return 0 ;
}
