
/**
 *    author        : Sudipta Banik Trisha
 *    created       : 01/09/2021 23:07:04
 *    Problem Name  : A. AquaMoon and Two Arrays
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1546/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll a[n],b[n],sum1=0, sum2=0;
    for(ll i=0; i<n; i++) {
        cin >> a[i];
        sum1+=a[i];
    }
    for(ll i=0; i<n; i++) {
        cin >> b[i];
        sum2+=b[i];
    }

    if(sum1 != sum2){
        cout << "-1" << endl;
        return ;
    }

    vector<pair<ll,ll> >v;

    for(ll i=0; i<n; i++) {
        for(ll j=0; j<n; j++) {
            while(a[i] > b[i] && a[j] < b[j]) {
                a[i]--,a[j]++;
                v.push_back(make_pair(i+1,j+1));
            }
        }
    }

    cout << v.size()<< endl;
    for(auto &x: v){
        cout << x.first << " " << x.second << endl;
    }
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;
    while(test--){
        solve();
    }

    return 0 ;
}
