
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 11/05/2021 12:27:37
 *    Problem Name  : B. Valuable Resources
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/485/B
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll mx_x = INT_MIN, mn_x = INT_MAX, mx_y = INT_MIN, mn_y = INT_MAX;

    for(ll i=1; i<=n; i++) {
        ll x,y;
        cin >> x >> y;

        mx_x = max(mx_x , x);
        mn_x = min(mn_x , x);

        mx_y = max(mx_y , y);
        mn_y = min(mn_y , y);
    }

    ll ans = max((mx_x - mn_x), (mx_y - mn_y));
    cout << ans*ans << endl;
}

int main(){
    ios_base::sync_with_stdio(false);
    solve();

    return 0 ;
}
