
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 18/08/2021 21:55:41
 *    Problem Name  : A. Cherry
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1554/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll a[n];
    for(ll i=0; i<n; i++) {
        cin >> a[i];
    }

    ll temp = a[0]*a[1];

    for(ll i=1; i<n-1; i++) {
        temp = max(temp , (a[i]*a[i+1]));
    }

    cout << temp << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;
    while(test--){
        solve();
    }

    return 0 ;
}
