
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 22/05/2021 11:19:10
 *    Problem Name  : A. And Then There Were K
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1527/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll digit;
    for(ll i=0; i<30; i++) {
        if((n>>i)&1) digit = i;
    }

    ll ans = (1<<digit)-1;
    cout << ans << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }
    return 0 ;
}
