
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 24/05/2021 22:14:21
 *    Problem Name  : A. Array and Peaks
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1513/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n,k;
    cin >> n >> k;

    if(n <= 2*k) {
        cout << "-1" << endl;
    }

    else {
        vector<ll>v(n);
        for(ll i=0; i<n; i++) v[i] = i+1;

        ll i=1;
        while(k > 0) {
            swap(v[i],v[i+1]);
            k--;
            i+=2;
        }
        for(auto x: v) cout << x << " ";
        cout << endl;
    }
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }

    return 0 ;
}
