
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 01/06/2021 13:12:52
 *    Problem Name  : C. Fibonacci Words
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/contest/1505/problem/C
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
using namespace std;

void solve()
{
    string s;
    cin >> s;

    int sz = s.length();
    vector<int>v(sz);

    for(int i=0; i<sz; i++) {
        v[i] = s[i] - 'A';
    }

    for(int i=2; i<sz; i++) {
        if((v[i-1] + v[i-2])%26 != v[i]){
            cout << "NO" << endl;
            return ;
        }
    }

    cout << "YES" << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    solve();

    return 0 ;
}
