
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 17/08/2021 22:31:36
 *    Problem Name  : A. PizzaForces
 *    Problem Limit : 2000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1555/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll num;
    cin >> num;

    cout << max(num+1,6LL)/2*5 << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }

    return 0 ;
}
