
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 29/05/2021 11:10:43
 *    Problem Name  : B1. Palindrome Game (easy version)
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1527/B1
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    string s;
    cin >> s;

    ll zero=0;
    for(ll i=0; i<n; i++) {
        if(s[i] == '0') zero++;
    }

    if(zero == 1) cout << "BOB" << endl;

    else if(zero % 2 == 0) {
        cout << "BOB" << endl;
    }

    else cout << "ALICE" << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }



    return 0 ;
}
