
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 17/08/2021 21:38:58
 *    Problem Name  : A. Ezzat and Two Subsequences
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1557/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll arr[n],sum=0;
    for(ll i=0; i<n; i++) {
        cin >> arr[i];
        sum = sum + arr[i];
    }

    sort(arr,arr+n);
    ll mx = *max_element(arr,arr+n);
    double temp = sum - mx;
    double total = 1.0*(temp/(n-1) + mx);

    cout << fixed << setprecision(9) << total << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }


    return 0 ;
}
