
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 26/05/2021 13:25:43
 *    Problem Name  : A. Strange Table
 *    Problem Limit : 2000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1506/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n,m,x;
    cin >> n >> m >> x;

    ll col = (x-1) / n;
    ll row = (x-1) % n;

    cout << row*m + col + 1 << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }


    return 0 ;
}
