
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 06/05/2021 11:51:27
 *    Problem Name  : A. Do Not Be Distracted!
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/contest/1520/problem/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    string s;
    cin >> s;

    bool flag = true;
    map<char,ll>mp;
    mp[s[0]]++;
    for(ll i=0; i<n; i++) {
        if(s[i] != s[i+1] && mp[s[i+1]] > 0) {
            flag = false;
            cout << "NO" << endl;
            return ;
        }
        mp[s[i+1]]++;
    }

    cout << "YES" << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }
    return 0 ;
}
