
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 31/05/2021 21:07:19
 *    Problem Name  : A. Mean Inequality
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1526/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll a[2*n];
    for(ll i=0; i<2*n; i++) cin >> a[i];

    sort(a,a+2*n);

    for(ll i=0; i<n; i++) {
        cout << a[i] << " " << a[i+n] << " ";
    }
    cout << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }

    return 0 ;
}
