
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 01/06/2021 12:57:30
 *    Problem Name  : B. DMCA
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/contest/1505/problem/B
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll ans = n % 9;

    if(ans == 0) ans = 9;
    cout << ans << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    solve();

    return 0 ;
}
