
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 11/05/2021 13:13:11
 *    Problem Name  : A. Fox and Number Game
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/389/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll num[n];
    for(ll i=0; i<n; i++) 
        cin >> num[i];

    ll ans = num[0];
    for(ll i=0; i<n; i++) {
        ans = __gcd(ans,num[i]);
    }

    cout << ans * n << endl;
}

int main(){
    ios_base::sync_with_stdio(false);

    solve();
    return 0 ;
}
