
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 08/05/2021 10:44:35
 *    Problem Name  : A. Nastia and Nearly Good Numbers
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/contest/1521/problem/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll a,b;
    cin >> a >> b;

    if(b == 1){
        cout << "NO" << endl;
    }
    else {
        cout << "YES" << endl;
        cout << a << " " << a*(b*2-1) << " " << a*b*2 << endl;
    }
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }

    return 0 ;
}
