
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 01/06/2021 12:42:49
 *    Problem Name  : A. Is it rated - 2
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1505/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
using namespace std;

void solve()
{
    string s;
    while(getline(cin,s)) {
        cout << "NO" << endl;
    }
}

int main(){
    ios_base::sync_with_stdio(false);

    solve();
    return 0 ;
}
