
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 24/05/2021 13:57:15
 *    Problem Name  : A. Phoenix and Gold
 *    Problem Limit : 2000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1515/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n, x;
    cin >> n >> x;

    vector<ll>a(n);
    ll sum = 0;
    for(ll i=0; i<n; i++) {
        cin >> a[i];
        sum += a[i];
    }

    if(sum == x) {
        cout << "NO" << endl;
    }

    else {
        cout << "YES" << endl;
        
        ll s = 0, pos;
        for(ll i=0; i<n; i++) {
            s += a[i];
            if(s == x) {
                swap(a[i], a[i+1]);      
            }

            cout << a[i] << " ";
        }
        cout << endl;
    }
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--) {
        solve();
    }

    return 0 ;
}
