
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 15/05/2021 15:26:04
 *    Problem Name  : A. XORwice
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/problemset/problem/1421/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int
using namespace std;

void solve()
{
    ll a,b;
    cin >> a >> b;

    ll result = a ^ b;
    cout << result << endl;
}

int main(){
    ios_base::sync_with_stdio(false);
    ll test;
    cin >> test;
    while(test--)
        solve();

    return 0 ;
}
