
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 08/05/2021 15:28:42
 *    Problem Name  : B. Nastia and a Good Array
 *    Problem Limit : 2000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/contest/1521/problem/B
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int 
using namespace std;

void solve()
{
    ll n;
    cin >> n;

    ll a[n+1];
    ll min_val=INT_MAX , position;
    for(ll i=1; i<=n; i++) {
        cin >> a[i];
        if(min_val > a[i]) {
            min_val = a[i];
            position = i;
        }
    }

    cout << n-1 << endl;
    for(ll i=1; i<=n; i++) {
        if(i == position) continue;

        cout << position << " " << i << " " << min_val << " " << min_val + abs(position-i) << endl;
    }
}

int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;
    while(test--) {
        solve();
    }
    return 0 ;
}
