
/**
 *    author        : Sudipta Banik Trisha 
 *    created       : 05/05/2021 11:33:05
 *    Problem Name  : A. Red and Blue Beans
 *    Problem Limit : 1000 ms , 256 MB
 *    Problem Url   : https://codeforces.com/contest/1519/problem/A
 *    @generated by : ai-virtual-assistant
**/

#include<bits/stdc++.h>
#define ll long long int
using namespace std;

void solve()
{
    ll r,b,d;
    cin >> r >> b >> d;

    if(r > b) swap(r,b);

    ll temp = r*(d+1);
    if(temp < b) {
        cout << "NO" << endl;
    }

    else{
        cout << "YES" << endl;
    }
}
int main(){
    ios_base::sync_with_stdio(false);

    ll test;
    cin >> test;

    while(test--){
        solve();
    }

    return 0 ;
}
